### ISSUE TITLE
how do you compile it

### ISSUE THREAD

**Issue by z3roco01** [SolraBizna/logi6502#4] opened 2021-09-07 19:24 UTC
i want to compile it but cant figure out how

**Comment by SolraBizna** [comment] 2021-09-08 08:27
I'm afraid I won't be much help on this. It's been a long time since I did any Java work, and my pipeline at the time was pretty weird. It should be a simple matter of opening up the project with your favorite Java IDE, and hitting "Compile". Beyond that I have no idea.

If you're interested in compiling it just so you can use it, [you can download a pre-built jar from here](https://github.com/SolraBizna/logi6502/releases/tag/v1.0). If you're interested in modifying it, I'm sorry that I can't be of more help than this.

(Closing this issue, since it's not a bug report or feature request.)

**Closed as completed by SolraBizna** 2021-09-08 08:27 UTC
